### PR TITLE
Update ANMN reporting queries to use new anmn_metadata schema

### PR DESCRIPTION
**Pull request by mhidas**

### CODE REVIEW

**Comment by mhidas** [comment]
@xhoenner Please have a look when you can.

Not tested yet. I'll let you know when I have.

**Comment by mhidas** [comment]
I forgot to add that to be accurate we should rename `anmn_nrs_rt.sql` to just `anmn_rt.sql` and same for the views created within. This is because there are several realtime but non-NRS data streams in there now. However this may be more trouble than it's worth. Probably more important to update the report templates to reflect this change.

**Comment by xhoenner** [comment]
All good @mhidas, tested and fully functional, nice work. @jachope I've updated the ANMN Word template based on Marty's email.

**Comment by mhidas** [comment]
@xhoenner Thanks!

**Comment by jachope** [comment]
I have updated the iReport templates inline with the word template.  Xavier you will be able to review the output on Tuesday prior to publishing (can't show you all now as total table not available). 
Such minor changes I don't think there will be any issues.

**Comment by xhoenner** [comment]
Great, yes I can have a look at these on Tuesday.

**Comment by mhidas** [comment]
Thanks @jachope

**Pull request merged**
